services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - ENV=${ENV:-production}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - SETUP_DB_HOST=db
      - SETUP_DB_PORT=5432
      - SETUP_DB_USER=${POSTGRES_USER}
      - SETUP_DB_PASS=${POSTGRES_PASSWORD}
      - SETUP_DB_NAME=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=${ENV:-production}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
    depends_on:
      - db
    volumes:
      - ./:/app

  frontend:
    build:
      context: ./pentest-frontend
      dockerfile: Dockerfile
    container_name: erp-frontend
    restart: always
    ports:
      - "80:8080"      # Standard HTTP (Redirects to HTTPS)
      - "443:8443"     # Standard HTTPS (Secure Traffic)
    volumes:
      # MAGIC: Mount the SSL folder into Nginx
     - ~/erp-ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend

# NEW: Declare the Named Volume so Docker knows to create it with the right permissions
volumes:
  pgdata: