ALTER TABLE users ADD COLUMN IF NOT EXISTS start_year INTEGER DEFAULT 2024;
ALTER TABLE users ADD COLUMN IF NOT EXISTS end_week INTEGER DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS end_year INTEGER DEFAULT NULL;